### ISSUE TITLE
Feature requests (matches pull request #12)

### ISSUE THREAD

**Issue by Kaisonic** [Cu3PO42/KeySAV2#13]
- Added available columns: Level, Region, Country, Held Item, Language, Game, Number, PID, Mark, Dex Number, Form
- Fixed "mark" - pentagon mark is now present for all Pokemon created in generation 6
- Fixed "Number" column to be 1-indexed
- Fixed help box to be resizable and able to be kept open while working in the main window
- Added ORAS game support for "Game" and "Region" values
- Fixed superfluous spaces in CSV data
- Added perfect IV marker columns
- Added perfect IV counter column
- Added IV and EV sum columns
- Changed pk6 file output to be in box order rather than species order (for better PkHex support)
- Code refactoring (combined dumpPKX_BV and dumpPKX_SAV)
- Added option to show ESV for hatched Pokemon
- Added option to enclose trainer and Pokemon nicknames in quotes for CSV exports (to prevent problems with commas in either)
- Added option to use legacy save-twice file-breaking behavior (click "What's this?" in the app for more info)
- Added "Egg Received" and "Met/Hatched" columns

**Comment by Cu3PO42** [comment]
As described in pull request, I will start selectively merging features soon.
