### ISSUE TITLE
Depending on break save states, decryption of certain slots sometimes never completes

### ISSUE THREAD

**Issue by Kaisonic** [Cu3PO42/KeySAV2#19]
If the saves used to break encryption (save1, save2, save3, a.k.a. 26.sav, 16.sav, 165.sav) contain Pokemon in boxes other than 1 and 2, decryption of some slots fails, resulting in no Pokemon listed in a slot where there is Pokemon, and listing <100% Pokemon in slots that are empty.

For example, if I break encryption using three saves that contain ONLY the six Pokemon in the proper spots in the first two boxes, then I open saves that are empty, full1, and full2, decryption is fully successful. When I then re-open empty, no Pokemon appear, and when I re-open full1 or full2, all 930 Pokemon appear with no ~ markers. This is correct behavior.

However, if I break encryption using three saves that contain only the proper six Pokemon in the first two boxes, but the rest of the boxes contain random Pokemon, then I open the SAME three saves (empty, full1, full2), decryption is not fully successful. When I re-open empty, a single ~ marked Pokemon appears. When I re-open full1 or full2, only 929 Pokemon appear, and the slot that does not appear matches the slot that appeared in empty with the ~ marker.

Is there a way to ignore all other boxes in the initial decryption so subsequent decryptions are fully successful, regardless of the state of other boxes in the initial decryption saves?

(also submitted issue on official KeySAV2 GitHub on kwsch

**Comment by Cu3PO42** [comment]
This appears to be an issue with the original algorithm and not my code. As such I will close here and we will discuss it over there.
