### ISSUE TITLE
JPN and KOR text cause visual oddities in dumped data

### ISSUE THREAD

**Issue by anternika** [Cu3PO42/KeySAV2#22]
When dumping pokemon data that includes foreign characters, the font/tileset is changed for the foreign characters but is not switched back to standard characters afterwards. Included is an image of the bug (with JPN characters) in KeySAV2 and in WordPad. KOR characters produce a similar, yet slightly different visual effect.

This text displayed as expected on reddit, Microsoft Word, Sublime Text 2, and Notepad. It displayed improperly in WordPad and the KeySAV2 interface.

http://i.imgur.com/m7fNsrt.png
http://i.imgur.com/TlUqj4r.png

**Comment by Cu3PO42** [comment]
I managed to reproduce it. This bug is, however, not caused by bad code in KeySAV2, but apparentlly is a problem with WinForms' handling of Unicode characters. There is nothing I can do about it right now. Sorry :/
